version: "3.8"
networks:
  natours:
    driver: bridge
services:
  back-end:
    container_name: fastapi
    build:
      context: .
    image: pedrojunqueira/natours-fastapi

    networks:
      - natours
  frontend:
    container_name: vue
    build:
      context: ./natours-frontend
    image: pedrojunqueira/natours-vue
    ports:
      - 80:80
    env_file:
      - ./natours-frontend/.env
    depends_on:
      - back-end
    networks:
      - natours
